'use strict';

const fs = require('fs');
const path = require('path');

/*
 * 所有 engine/*.js 都会进入浏览器 bundle。stage 只表达依赖层次，
 * 同层按文件名排序，因而新增模块仍具备确定性顺序。
 */
function stageFor(filename) {
  const name = String(filename).toLowerCase();
  if (name === 'requirement-spec.js') return 5;
  if (/color|theme/.test(name)) return 10;
  if (/symbol/.test(name)) return 20;
  if (/standard/.test(name)) return 30;
  if (/connector-library/.test(name)) return 40;
  if (name === 'evidence-library.js') return 41;
  if (/component-library/.test(name)) return 42;
  if (name === 'reference-system-library.js') return 43;
  if (name === 'board-circuit-library.js') return 44;
  if (/device-catalog|catalog|library/.test(name)) return 45;
  if (/design-model|netlist|topology|compiler/.test(name)) return 50;
  if (name === 'loop-integrity.js') return 54;
  if (/\berc\b|validation/.test(name)) return 55;
  if (name === 'rendered-svg-audit.js') return 59;
  if (/drawing-skill|rule|audit/.test(name)) return 60;
  if (/vendor/.test(name)) return 65;
  if (name === 'engine.js') return 70;
  /* v2.7.1-INTEG-C1: 参考知识库必须在 engineering-bom.js（取证层）之前加载，
   * 否则 BOM 构建时 window.EVSE_BOM_KNOWLEDGE 尚未挂载，参考列会全空。 */
  if (name === 'bom-library.js' || name === 'knowledge-inquiry.js') return 46;
  if (/layout|placement|sheet-planner/.test(name)) return 80;
  if (/drawing-ir|geometry/.test(name)) return 84;
  if (/router|routing|crossing/.test(name)) return 86;
  if (/editor/.test(name)) return 88;
  if (/draw-pile|renderer|render/.test(name)) return 90;
  if (/dxf|export/.test(name)) return 95;
  return 68;
}

function orderedEngineFiles(engineDir) {
  return fs.readdirSync(engineDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith('.js'))
    .map((entry) => entry.name)
    .sort((left, right) => stageFor(left) - stageFor(right) || left.localeCompare(right, 'en'));
}

function buildBrowserBundle(engineDir) {
  const files = orderedEngineFiles(engineDir);
  const header = [
    '/* AUTO-GENERATED by scripts/sync-web.js. DO NOT EDIT.',
    ' * Sources: ' + files.join(', '),
    ' */'
  ].join('\n');
  const body = files.map((filename) => {
    const source = fs.readFileSync(path.join(engineDir, filename), 'utf8').replace(/^\uFEFF/, '');
    return '\n/* ===== engine/' + filename + ' ===== */\n' + source.trimEnd() + '\n';
  }).join('');
  return header + '\n' + body;
}

module.exports = { stageFor, orderedEngineFiles, buildBrowserBundle };
